test lint

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,17 +1,22 @@
-# Run the formatting command
-npm run format
+# # Run the formatting command
+# npm run format
 
-# Check for changes after formatting
-if [ -n "$(git diff --name-only)" ]; then
-  echo "Unstaged changes detected after formatting. Please stage them before committing."
-  exit 1
-fi
+# # Check for changes after formatting
+# if [ -n "$(git diff --name-only)" ]; then
+#   echo "Unstaged changes detected after formatting. Please stage them before committing."
+#   exit 1
+# fi
 
-# Run the linting command
-npm run lint
+# # Run the linting command
+# npm run lint
 
-# Check for any linting errors
-if [ $? -ne 0 ]; then
-  echo "Linting errors detected. Please fix them before committing."
-  exit 1
-fi
+# # Check for any linting errors
+# if [ $? -ne 0 ]; then
+#   echo "Linting errors detected. Please fix them before committing."
+#   exit 1
+# fi
+
+#!/usr/bin/env sh
+. "$(dirname "$0")/_/husky.sh"
+
+npx lint-staged
